NODE_URL = "http://node.deviceproof.org:14265"
# NODE_URL = "http://node1.puyuma.org:14265"
SEED = "RBYYYKDIUDXV9Z9FQPFJSA9QQIGFZAS9XXAWHSDPPXYR9ULXZWYNQSOOYHOXSNXEORWGRIQXXINRHKTCU"
DEPTH = 3
MIN_WEIGHT_MAGNITUDE = 14
